apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kafka }}
  labels:
    app: kafka
    app.kubernetes.io/component: message-broker
type: Opaque
stringData:
  # Auth service Kafka
  AUTH_KAFKA_CLIENT_ID: auth-service
  # Payment service Kafka
  PAYMENT_KAFKA_CLIENT_ID: payment-service