apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres }}
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.data.postgres.user | default "ishimwe" | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.data.postgres.password | default "2025New+" | quote }}
  # Use placeholders or let each overlay override what it needs
  DB_NAME: {{ .Values.config.auth.postgresDb | default "authdb" | quote }}
  DB_USER: {{ .Values.secrets.data.postgres.user | default "ishimwe" | quote }}
  DB_PASSWORD: {{ .Values.secrets.data.postgres.password | default "2025New+" | quote }}