# Generated by Django 5.2.6 on 2026-01-03 13:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMProfile',
            fields=[
                ('user_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('unread_notifications_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('phone', models.CharField(blank=True, help_text='E.164 format (e.g., +14155552671)', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in valid E.164 format (e.g., +14155552671).', regex='^\\+[1-9]\\d{6,14}$')])),
                ('location', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Location must be a valid 2-letter uppercase country code (e.g., US).', regex='^[A-Z]{2}$')])),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('theme', models.CharField(default='system', max_length=50)),
                ('avatar', models.URLField(blank=True, default=None, null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Primary Profile',
                'verbose_name_plural': 'Primary Profiles',
                'db_table': 'profiles',
                'indexes': [models.Index(fields=['-followers_count'], name='profile_followers_idx'), models.Index(fields=['is_deleted'], name='profile_is_deleted_idx'), models.Index(fields=['account_type'], name='profile_account_type_idx'), models.Index(fields=['location'], name='profile_location_idx')],
            },
        ),
    ]
