apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app: auth-service
    app.kubernetes.io/component: auth-service
data:
  # Service Identity
  SERVICE_NAME: {{ .Values.config.auth.serviceName | quote }}
  DB_NAME: {{ .Values.config.auth.dbName | quote }}
  
  # Django Core
  DJANGO_SETTINGS_MODULE: {{ .Values.config.auth.djangoSettingsModule | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.config.auth.djangoAllowedHosts | quote }}
  DJANGO_DEBUG: {{ .Values.config.auth.djangoDebug | quote }}
  LOG_LEVEL: {{ .Values.config.auth.logLevel | quote }}
  
  # Database
  POSTGRES_HOST: {{ .Values.config.auth.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.config.auth.postgresPort | quote }}
  DB_HOST: {{ .Values.config.auth.dbHost | quote }}
  DB_PORT: {{ .Values.config.auth.dbPort | quote }}
  
  # RabbitMQ
  RABBITMQ_HOST: {{ .Values.config.auth.rabbitmqHost | quote }}
  RABBITMQ_QUEUE: {{ .Values.config.auth.rabbitmqQueue | quote }}
  RABBITMQ_VHOST: {{ .Values.config.auth.rabbitmqVhost | quote }}
  
  # Kafka
  KAFKA_BROKERS: {{ .Values.config.auth.kafkaBrokers | quote }}
  KAFKA_TOPIC: {{ .Values.config.auth.kafkaTopic | quote }}
  KAFKA_GROUP_ID: {{ .Values.config.auth.kafkaGroupId | quote }}
  
  # Redis
  REDIS_HOST: {{ .Values.config.auth.redisHost | quote }}
  
  # URLs
  AUTH_PUBLIC_KEY_URL: {{ .Values.config.auth.authPublicKeyUrl | quote }}
  
  # CORS
  CORS_ALLOWED_ORIGINS: {{ .Values.config.auth.corsAllowedOrigins | quote }}
  CSRF_TRUSTED_ORIGINS: {{ .Values.config.auth.csrfTrustedOrigins | quote }}
  CORS_ALLOW_CREDENTIALS: {{ .Values.config.auth.corsAllowCredentials | quote }}
  
  # Channel Layers
  CHANNEL_LAYER_HOSTS: {{ .Values.config.auth.channelLayerHosts | quote }}